Feat assignment 8 memory management basic profiling
aristovinceselvanathan/TIPS pull request #10
Opened 2023-09-05 17:47 UTC by aristovinceselvanathan

2023-09-14 15:55 UTC, sandeep-sol requested changes

2023-09-14 15:55 UTC, sandeep-sol commented on src/Assignment8/MemoryEater.cs
> +                    for (int i = 0; i < maxArrays; i++)
Why is there a for loop inside a while loop? is this intentional?

2023-09-14 15:55 UTC, sandeep-sol commented on src/Assignment8/Readme.md
> +## Documentation Report:
Could you please add some pictures and metrics from your observation?

2023-09-14 15:55 UTC, sandeep-sol commented on src/Assignment8/Readme.md
> +### Description
Also, please try to implement this code in some other approaches and get those observations as well. This will clearly indicate what is the difference between the current approach and other approaches.

2023-09-15 08:25 UTC, aristovinceselvanathan commented on src/Assignment8/Readme.md
> +## Documentation Report:
I have added the pictures into observation

2023-09-15 08:25 UTC, aristovinceselvanathan commented on src/Assignment8/Readme.md
> +### Description
I have other ways to implement it.

2023-09-25 04:35 UTC, sandeep-sol requested changes

2023-09-25 04:35 UTC, sandeep-sol commented on src/Assignment8/PerformanceProfiler/02-MemoryOptimization1.png
Please name these files with the approach that you've followed to optimize the memory.

2023-09-25 04:35 UTC, sandeep-sol commented on src/Assignment8/Program.cs
> +        /// <param name="strings">It takes the string array from the command line interface</param>
This param description needs to be updated. I've conveyed this in the previous assignments.

2023-09-25 04:35 UTC, sandeep-sol commented on src/Assignment8/Readme.md
> +The program continuously consumes memory by allocating the int array size of 100 to the list, and the garbage collector triggers less frequently to clear up the unused memory. The size of the heap al
size of 100? What is this number?

2023-09-25 04:35 UTC, sandeep-sol commented on src/Assignment8/Readme.md
> +To improve this code, add a way to limit the amount of memory allocated or provide a way to clean up allocated resources when they are no longer needed, and make the array out of reference by bringin
Is making the array out of scope, a good approach? Won't that really depend on the use case? 

And I hope that in most of the use cases, the user/developer will need the value in the array to be persisted.

Please update this point considering all the applicable use cases.

2023-09-25 04:35 UTC, sandeep-sol commented on src/Assignment8/Readme.md
> +```public class MemoryEater
The code should be started from the next line after the ticks so that it will be shown as a code in preview and not as a normal string.

2023-09-25 04:35 UTC, sandeep-sol commented on src/Assignment8/Readme.md
> +### Real-time Problems
It's good that you've listed down the possible issues. 

However, the given items are not real-time problems. Please explore and update this section.

2023-09-25 08:41 UTC, aristovinceselvanathan commented on src/Assignment8/Readme.md
> +### Real-time Problems
I have added the more specific real-time problems.

2023-09-25 08:43 UTC, aristovinceselvanathan commented on src/Assignment8/Readme.md
> +```public class MemoryEater
I have rectified.

2023-09-25 08:43 UTC, aristovinceselvanathan commented on src/Assignment8/Readme.md
> +To improve this code, add a way to limit the amount of memory allocated or provide a way to clean up allocated resources when they are no longer needed, and make the array out of reference by bringin
I have updated the use case.

2023-09-25 08:44 UTC, aristovinceselvanathan commented on src/Assignment8/Readme.md
> +The program continuously consumes memory by allocating the int array size of 100 to the list, and the garbage collector triggers less frequently to clear up the unused memory. The size of the heap al
I have rectified it

2023-09-25 08:44 UTC, aristovinceselvanathan commented on src/Assignment8/Program.cs
> +        /// <param name="strings">It takes the string array from the command line interface</param>
I have added summary.

2023-09-25 08:45 UTC, aristovinceselvanathan commented on src/Assignment8/PerformanceProfiler/02-MemoryOptimization1.png
I have updated file name.

2023-09-25 08:46 UTC, aristovinceselvanathan commented on src/Assignment8/MemoryEater.cs
> +                    for (int i = 0; i < maxArrays; i++)
I have updated the logic

2023-09-27 16:53 UTC, sandeep-sol approved these changes

2023-09-28 10:29 UTC, merged