Feat assignment 11 Error Handling
aristovinceselvanathan/TIPS pull request #11
Opened 2023-09-15 10:23 UTC by aristovinceselvanathan

Overview:
- This program provides examples of different error handling techniques that developers can use in their own code. 
- Program covers use of the try, catch, finally blocks and use of AppDomain to trigger the event when the unhandled exception occurs.

2023-09-27 17:21 UTC, sandeep-sol requested changes

2023-09-27 17:21 UTC, sandeep-sol commented on src/Assignment11/ErrorHandling/Program.cs
> +        public static void DivideByZero(int[] array)
This function is not doing what we expect it to do. Please revisit this.

2023-09-27 17:21 UTC, sandeep-sol commented on src/Assignment11/ErrorHandling/Program.cs
> +            try
Why use nested try...catch block here?

2023-09-27 17:21 UTC, sandeep-sol commented on src/Assignment11/ErrorHandling/Readme.md
Why is this file showing as a BIN file? Please find the reason and covert the file.

2023-09-28 09:46 UTC, aristovinceselvanathan commented on src/Assignment11/ErrorHandling/Program.cs
> +        public static void DivideByZero(int[] array)
I have changed the function.

2023-09-28 09:46 UTC, aristovinceselvanathan commented on src/Assignment11/ErrorHandling/Program.cs
> +            try
I have removed the nested try block.

2023-09-28 09:47 UTC, aristovinceselvanathan commented on src/Assignment11/ErrorHandling/Readme.md
I have changed the encoding of the file

2023-10-04 16:06 UTC, sandeep-sol requested changes

2023-10-04 16:06 UTC, sandeep-sol commented on src/Assignment11/ErrorHandling/Program.cs
> +        public static void DivideByZero(int enteredNumber)
The requirement is to implement code that handles the possible DivideByZeroException from user inputs and not to hardcode anything here.

2023-10-04 16:06 UTC, sandeep-sol commented on src/Assignment11/ErrorHandling/Program.cs
> +        public static void IndexOutOfBound(int[] array)
Try to handle a proper user scenario instead of just hardcoding the expected logic.

2023-10-04 16:06 UTC, sandeep-sol commented on src/Assignment11/ErrorHandling/Program.cs
> +                        WarningMessage(exception.Message);
Why is the console not being cleared in this case alone?

2023-10-04 16:06 UTC, sandeep-sol commented on src/Assignment11/ErrorHandling/Program.cs
> +                Console.Write("Choose which error wanted to raise 1.Divide By Zero, 2.Index Out of Range, 3.UnHandled Exception 4.Exit: ");
These are user-visible strings. 

Use some line breaks, and indentations and make it more user-friendly to read.

2023-10-04 16:06 UTC, sandeep-sol commented on src/Assignment11/ErrorHandling/Readme.md
> +- Modify the Task 1 program with an integer array, add a try/catch block for IndexOutOfRangeException, throw a custom exception with a message, and catch and print that new exception's message.
Are you throwing a custom exception? I don't think so.

2023-10-04 16:06 UTC, sandeep-sol commented on src/Assignment11/ErrorHandling/Readme.md
> +- I have created the custom exception InValidUserInput by inherit the exception class, in the constructor part need to pass the message to the constructor of exception class.
```suggestion
- I have created the custom exception InvalidUserInput by inherit the exception class, in the constructor part need to pass the message to the constructor of exception class.
```

Invalid is a single word.

2023-10-04 16:06 UTC, sandeep-sol commented on src/Assignment11/ErrorHandling/Readme.md
> +- By this user - defined exception is created and implemented in the testing the input of the user, if input is not valid then it will throw the exception.
This statement is not meaningful. Please update it.

2023-10-04 16:06 UTC, sandeep-sol commented on src/Assignment11/ErrorHandling/Readme.md
> +In this code, it asks the user to enter the type of execution to be thrown and to handle it using the try and catch block. The custom-type exception created by the inheritance of the exception class
```suggestion
In this code, it asks the user to enter the type of Exception to be thrown and to handle it using the try and catch block. The custom-type exception created by the inheritance of the exception class to the class The Appdomain helps in the use of the event handler before the exception is caught by the OS layer.
```

2023-10-04 16:06 UTC, sandeep-sol commented on src/Assignment11/ErrorHandling/Program.cs
> +            catch (IndexOutOfRangeException)
Please read through the requirements for Task 2 once again.

This part of code need to be updated.

2023-10-04 16:06 UTC, sandeep-sol commented on src/Assignment11/ErrorHandling/Readme.md
> +I have used the try and catch block to handle the zero division error and checking the finally will be executed always. To create the zero division error in the code created empty array and tried to
Array?

2023-10-05 12:05 UTC, aristovinceselvanathan commented on src/Assignment11/ErrorHandling/Program.cs
> +        public static void DivideByZero(int enteredNumber)
I have updated the logic

2023-10-05 12:05 UTC, aristovinceselvanathan commented on src/Assignment11/ErrorHandling/Program.cs
> +                        WarningMessage(exception.Message);
I have updated the logic

2023-10-05 12:05 UTC, aristovinceselvanathan commented on src/Assignment11/ErrorHandling/Program.cs
> +        public static void IndexOutOfBound(int[] array)
I have updated the logic

2023-10-05 12:06 UTC, aristovinceselvanathan commented on src/Assignment11/ErrorHandling/Program.cs
> +                Console.Write("Choose which error wanted to raise 1.Divide By Zero, 2.Index Out of Range, 3.UnHandled Exception 4.Exit: ");
I have changed the user visible string

2023-10-05 12:07 UTC, aristovinceselvanathan commented on src/Assignment11/ErrorHandling/Readme.md
> +- Modify the Task 1 program with an integer array, add a try/catch block for IndexOutOfRangeException, throw a custom exception with a message, and catch and print that new exception's message.
I have changed the statement.

2023-10-05 12:07 UTC, aristovinceselvanathan commented on src/Assignment11/ErrorHandling/Readme.md
> +- I have created the custom exception InValidUserInput by inherit the exception class, in the constructor part need to pass the message to the constructor of exception class.
I have updated it.

2023-10-05 12:07 UTC, aristovinceselvanathan commented on src/Assignment11/ErrorHandling/Readme.md
> +In this code, it asks the user to enter the type of execution to be thrown and to handle it using the try and catch block. The custom-type exception created by the inheritance of the exception class
I have updated it

2023-10-05 12:08 UTC, aristovinceselvanathan commented on src/Assignment11/ErrorHandling/Readme.md
> +I have used the try and catch block to handle the zero division error and checking the finally will be executed always. To create the zero division error in the code created empty array and tried to
I have updated it

2023-10-05 12:09 UTC, aristovinceselvanathan commented on src/Assignment11/ErrorHandling/Program.cs
> +            catch (IndexOutOfRangeException)
I have removed it

2023-10-05 12:09 UTC, aristovinceselvanathan commented on src/Assignment11/ErrorHandling/Readme.md
> +- By this user - defined exception is created and implemented in the testing the input of the user, if input is not valid then it will throw the exception.
I have changed the statement

2023-10-11 15:00 UTC, sandeep-sol approved these changes

2023-10-11 15:00 UTC, sandeep-sol commented on .gitignore
> +/src/Assignment18/FileDataProcessor/source.txt
Please make this change in Assignment18 and not here.

2023-10-11 15:00 UTC, sandeep-sol commented on src/Assignment11/ErrorHandling/InvalidUserInputException.cs
> +    /// It is exception class to handle the invalid user
```suggestion
    /// Exception class to handle the invalid user.
```

2023-10-11 15:00 UTC, sandeep-sol commented on src/Assignment11/ErrorHandling/InvalidUserInputException.cs
> +        /// <param name="message">User Entered Message to throw exception</param>
This message is given by the developer and not by the user. Please update it accordingly.

2023-10-11 15:00 UTC, sandeep-sol commented on src/Assignment11/ErrorHandling/InvalidUserInputException.cs
> +            : base($"{message}")
Why can't we pass the `message` directly? What is the need for string interpolation here?

2023-10-11 15:00 UTC, sandeep-sol commented on src/Assignment11/ErrorHandling/InvalidUserInputException.cs
> +            Console.ForegroundColor = ConsoleColor.Red; // It sets the color of the console text.
The code itself is understandable here. You shall remove the comment.

Adding comments to code is good practice. But that should be done only for very complex code and not for simple codes.

And one another thing to mention here is, we should write the code in such a way that it is easily understandable without any comments.

2023-10-11 15:00 UTC, sandeep-sol commented on src/Assignment11/ErrorHandling/Program.cs
> +                    catch (DivideByZeroException)
Nice 😀

2023-10-11 15:00 UTC, sandeep-sol commented on src/Assignment11/ErrorHandling/Program.cs
> +                        WarningMessage("\nNumber is Divided by Zero");
This should be like an info to the user - `Number cannot be divided by zero`

2023-10-11 15:00 UTC, sandeep-sol commented on src/Assignment11/ErrorHandling/Readme.md
> +# Documentation Report
There are many typo errors in the document. Please resolve those.

2023-10-14 12:09 UTC, aristovinceselvanathan commented on src/Assignment11/ErrorHandling/InvalidUserInputException.cs
> +    /// It is exception class to handle the invalid user
I have updated it

2023-10-14 12:10 UTC, aristovinceselvanathan commented on src/Assignment11/ErrorHandling/InvalidUserInputException.cs
> +        /// <param name="message">User Entered Message to throw exception</param>
I have updated it

2023-10-14 12:10 UTC, aristovinceselvanathan commented on src/Assignment11/ErrorHandling/InvalidUserInputException.cs
> +            : base($"{message}")
I have updated it

2023-10-14 12:10 UTC, aristovinceselvanathan commented on src/Assignment11/ErrorHandling/Program.cs
> +                        WarningMessage("\nNumber is Divided by Zero");
I have updated it

2023-10-14 12:11 UTC, aristovinceselvanathan commented on src/Assignment11/ErrorHandling/Readme.md
> +# Documentation Report
I have updated it

2023-10-14 12:38 UTC, merged