feat:Added C# Calculator Code
aristovinceselvanathan/TIPS pull request #3
Opened 2023-08-11 12:14 UTC by aristovinceselvanathan

I have completed assignment 1. Please review the assigment.

2023-08-12 14:06 UTC, aristovinceselvanathan commented
No, I Have  Completed. Can I Merge to main branch

2023-08-14 13:30 UTC, sandeep-sol commented on README.md
Why is this file removed?

2023-08-14 13:31 UTC, sandeep-sol commented on docs/Assignment1ExplorationQ.md
> +### 1. Explain what the .NET platform is nad its primary purpose.
typo mistake

2023-08-14 13:32 UTC, sandeep-sol commented on docs/Assignment1ExplorationQ.md
> +### 1. Explain what the .NET platform is nad its primary purpose.
Please go through this file thoroughly once. I see many typo mistakes.

2023-08-14 13:34 UTC, sandeep-sol commented on README.md
I see many files removed from the repo. That seems to be a significant change.

If it is unexpected, please revert (you should have got it in sef-review itself). If not, please state the reason for remving these files in the PR description.

2023-08-14 13:37 UTC, sandeep-sol commented on src/Assignment1/Program.cs
> +        /// <param name="args"> This is a sample args</param>
sample args? This can be more clear.

2023-08-14 13:38 UTC, sandeep-sol commented on src/Assignment1/Program.cs
> +            MathUtils cal = new MathUtils();
variable names should be more meaningful. The name `cal` should be changed.

2023-08-14 13:38 UTC, sandeep-sol commented on src/Assignment1/Program.cs
> +            MathUtils cal = new MathUtils();
Applicable for all the variables.

2023-08-14 13:40 UTC, sandeep-sol commented on src/Assignment1/Program.cs
> +            int input1 = Convert.ToInt32(Console.ReadLine());
What if the user enters an invalid number?

Say, the user enters a string instead of a number. Could you please think through these cases and update these logics?

2023-08-14 13:41 UTC, sandeep-sol commented on src/Assignment1/Program.cs
> +            int option = Convert.ToInt32(Console.ReadLine());
It will be good if the variable declarations goes in the top of the file.

2023-08-14 13:41 UTC, sandeep-sol commented on src/Assignment1/Program.cs
> +            Console.Write("Enter the options (1.Add, 2.Subtract, 3.Multiply, 4.Division, 5.Exit: ");
Typo in the user displayed string.

2023-08-14 13:42 UTC, sandeep-sol commented on src/Assignment1/Program.cs
> +            if (option == 1)
Isn't `switch` case a better option here instead of using multiple if..else?

2023-08-14 13:43 UTC, sandeep-sol commented on src/Assignment1/Program.cs
> +            Console.Write("First Number : ");
Why using Console.Write in some places and Console.Writeline in some places? 

I am sure you have some reason. But in some places, it will be mis aligning. Please check those things.

2023-08-14 13:44 UTC, sandeep-sol commented on src/Assignment1/Program.cs
> +    public class MathUtils
A file should contain only one class. Please move this class to a different file.

2023-08-14 13:44 UTC, sandeep-sol commented on src/Assignment1/Program.cs
> +    /// This is a Mathematical Calution Class
Typo here as well. Repeated in many places.

2023-08-14 13:45 UTC, sandeep-sol commented on src/Assignment1/Program.cs
> +        /// This is addtion fuction
Typo here as well.

2023-08-14 13:47 UTC, sandeep-sol commented on src/Assignment1/Program.cs
> +            return (float)((float)x / (float)y);
Won't float/float return a float? Why is the explicit type conversion needed?

2023-08-14 13:48 UTC, sandeep-sol commented on src/Assignment1/Program.cs
> +            return (float)((float)x / (float)y);
And the readme says that this function should return the quotient. If that is the case, the type conversion itself can be ignored.

2023-08-14 15:56 UTC, aristovinceselvanathan commented on README.md
This are readme files that are given for the reference for our purpose how to use the template. It our choice to remove or keep it

2023-08-16 13:54 UTC, sandeep-sol commented on src/Assignment1/Program.cs
> +                    goto label2;
I don't think the code has to be this complex.

Using Threads and goto.

Could you please update it with some simple logic.

2023-08-16 13:54 UTC, sandeep-sol commented on src/Assignment1/Program.cs
> +        /// <param name="args"> It is String array in the parameters of the main method</param>
This summary can be more clear.

2023-08-16 13:54 UTC, sandeep-sol commented on src/Assignment1/Program.cs
> +        private static bool flag1 = true;
static? What is the need for it?

2023-08-21 16:58 UTC, sandeep-sol commented
Please update the PR name. I guess I've already conveyed that. And please resolve the conversations which you've completed.

2023-08-21 17:01 UTC, sandeep-sol requested changes
This logic is too complex. Please simplify it.

2023-08-24 15:32 UTC, sandeep-sol requested changes

2023-08-24 15:32 UTC, sandeep-sol commented on docs/assets/git hooks script/pre-commit
Is there a valid reason this file was removed? 

This is a script to check if the branch name is proper or not. Removing it without any valid reason is not right.

2023-08-24 15:32 UTC, sandeep-sol commented on src/Assignment1/Program.cs
> +            bool match1, match2, match3, flag = true;
What is `match1` and `match2`? The functionality of the variables is not clear from the namings please update them.

2023-08-24 15:32 UTC, sandeep-sol commented on src/Assignment1/Program.cs
> +                        switch (option)
Why is the input greater than 5 cases not handled? I asked to handle it, right?

2023-08-24 15:32 UTC, sandeep-sol commented on src/ReadMe.txt
Please don't remove these files unnecessarily.

2023-08-27 15:01 UTC, sandeep-sol approved these changes

2023-08-28 06:23 UTC, aristovinceselvanathan commented on docs/Assignment1ExplorationQ.md
> +### 1. Explain what the .NET platform is nad its primary purpose.
I have rectified the typos in that line

2023-08-28 06:24 UTC, aristovinceselvanathan commented on src/Assignment1/Program.cs
> +        /// <param name="args"> This is a sample args</param>
Elaborated the comments .

2023-08-28 06:24 UTC, aristovinceselvanathan commented on src/Assignment1/Program.cs
> +            MathUtils cal = new MathUtils();
I have renamed the variable in a meaningful way.

2023-08-28 06:26 UTC, aristovinceselvanathan commented on src/Assignment1/Program.cs
> +            int input1 = Convert.ToInt32(Console.ReadLine());
I have changed the Convert.ToInt32() to int.TryParse() to check it is valid number.

2023-08-28 06:28 UTC, aristovinceselvanathan commented on src/Assignment1/Program.cs
> +            int option = Convert.ToInt32(Console.ReadLine());
Declaration of variables are declared in the top portion in the main method

2023-08-28 06:28 UTC, aristovinceselvanathan commented on src/Assignment1/Program.cs
> +            Console.Write("Enter the options (1.Add, 2.Subtract, 3.Multiply, 4.Division, 5.Exit: ");
I have added the closing curly braces.

2023-08-28 06:29 UTC, aristovinceselvanathan commented on src/Assignment1/Program.cs
> +            if (option == 1)
I have changed the if condition to the switch case.

2023-08-28 06:31 UTC, aristovinceselvanathan commented on src/Assignment1/Program.cs
> +    public class MathUtils
I have moved to the another class file.

2023-08-28 06:32 UTC, aristovinceselvanathan commented on src/Assignment1/Program.cs
> +    /// This is a Mathematical Calution Class
I have updated the typing mistakes

2023-08-28 06:32 UTC, aristovinceselvanathan commented on src/Assignment1/Program.cs
> +        /// This is addtion fuction
I have rectified it

2023-08-28 06:34 UTC, aristovinceselvanathan commented on src/Assignment1/Program.cs
> +            return (float)((float)x / (float)y);
I have changed the logic to return the quotient of the divison.

2023-08-28 06:38 UTC, aristovinceselvanathan commented on src/Assignment1/Program.cs
> +                    goto label2;
I have removed the goto and thread in the code and I have used the console.ReadKey() to stop the execution for some time.

2023-08-28 06:38 UTC, aristovinceselvanathan commented on src/Assignment1/Program.cs
> +        /// <param name="args"> It is String array in the parameters of the main method</param>
I have updated the statement

2023-08-28 06:40 UTC, aristovinceselvanathan commented on src/Assignment1/Program.cs
> +        private static bool flag1 = true;
I have changed it.

2023-08-28 06:40 UTC, aristovinceselvanathan commented on src/Assignment1/Program.cs
> +            bool match1, match2, match3, flag = true;
I have renamed to more meaningful way.

2023-08-28 06:41 UTC, aristovinceselvanathan commented on src/Assignment1/Program.cs
> +                        switch (option)
I have handled the case with the default in the switch case.

2023-08-28 06:41 UTC, aristovinceselvanathan commented on src/ReadMe.txt
I have added the file

2023-08-30 06:08 UTC, merged

2023-08-30 07:02 UTC, aristovinceselvanathan commented on src/Assignment1/Program.cs
> +            Console.Write("First Number : ");
I have updated the alignment of the lines.