feat: Contacts Manager Console Application Added
aristovinceselvanathan/TIPS pull request #4
Opened 2023-08-17 03:23 UTC by aristovinceselvanathan

2023-08-21 17:12 UTC, sandeep-sol requested changes

2023-08-21 17:12 UTC, sandeep-sol commented on src/Assignment2/Program.cs
> +        public static string NullException(string? input)
This is not how you check if the input is valid or not. Please update the logic.

2023-08-21 17:12 UTC, sandeep-sol commented on src/Assignment2/Program.cs
> +                    goto label1;
Please avoid using goto. I've conveyed this comment already.

2023-08-21 17:12 UTC, sandeep-sol commented on src/Assignment2/Program.cs
> +                try
Have you already started with Exception handling? If not please don't use try...catch. Replace it with other logic.

2023-08-21 17:12 UTC, sandeep-sol commented on src/Assignment2/Program.cs
> +            int id, i;
Why is the variable `i` declared here?

2023-08-21 17:12 UTC, sandeep-sol commented on src/Assignment2/Program.cs
> +        public static Person? SearchandRemove()
A function should not signify two operations. Please update the name accordingly.

2023-08-21 17:12 UTC, sandeep-sol commented on src/Assignment2/Program.cs
> +            int t;
The variable names are not understandable. Please update them.

2023-08-21 17:12 UTC, sandeep-sol commented on src/Assignment2/Program.cs
> +                        case 1:
Please prefer using enums instead of constant values.

2023-08-21 17:12 UTC, sandeep-sol commented on src/Assignment2/Program.cs
> +            bool phonec = person.SetPhone(phone);
What does this variable name mean? phonec, emailc?

2023-08-24 15:42 UTC, sandeep-sol requested changes

2023-08-24 15:42 UTC, sandeep-sol commented on src/Assignment2/Assignment2.csproj
> +    </PackageReference>
The alignment in this file is not proper. Please update it.

2023-08-24 15:42 UTC, sandeep-sol commented on src/Assignment2/Person.cs
> +        private string Name { get; set; }
You cannot say a variable to be private and have it with getters and setters. Please update it.

2023-08-24 15:42 UTC, sandeep-sol commented on src/Assignment2/Program.cs
> +        private static List<Person> list = new List<Person>();
The variable name is not right. Please update it.

2023-08-24 15:42 UTC, sandeep-sol commented on src/Assignment2/Program.cs
> +        private static List<Person> list = new List<Person>();
And what is the reason for having this variable as static?

2023-08-24 15:42 UTC, sandeep-sol commented on src/Assignment2/Program.cs
> +            int choose, option;
What is choose? Please have meaningful names.

2023-08-24 15:42 UTC, sandeep-sol commented on src/Assignment2/Program.cs
> +                Console.Write("Actions 1.Add 2.Remove 3.Search 4.Displyall 5.Exit: ");
Update this option

2023-08-24 15:42 UTC, sandeep-sol commented on src/Assignment2/Program.cs
> +                int.TryParse(Console.ReadLine(), out choose);
What if the input is not a valid number?

2023-08-24 15:42 UTC, sandeep-sol commented on src/Assignment2/Program.cs
> +                        Console.Write("Name: ");
What does this statement mean? Please be descriptive.

2023-08-24 15:42 UTC, sandeep-sol commented on src/Assignment2/Program.cs
> +                        if (IsValidString(name))
Why is this logic alone added here? And for others, added in the `Person` class.

2023-08-24 15:42 UTC, sandeep-sol commented on src/Assignment2/Program.cs
> +        public static Person? PersonSearch()
The function name is not meaningful.

2023-08-24 15:42 UTC, sandeep-sol commented on src/Assignment2/Program.cs
> +        public static string CheckStringIsNull(string? input)
This function is not doing what it's name signifies.

2023-08-24 15:42 UTC, sandeep-sol commented on src/Assignment2/Program.cs
> +        public static bool IsValidString(string input)
What is the criteria for a valid string?

2023-08-24 15:42 UTC, sandeep-sol commented on src/Assignment2/Program.cs
> +        public static void Displayall()
Function names should be in Pascal case. Please update it.

2023-08-28 06:45 UTC, aristovinceselvanathan commented on src/Assignment2/Program.cs
> +        public static string NullException(string? input)
I have removed the Null Exception logic.

2023-08-28 06:45 UTC, aristovinceselvanathan commented on src/Assignment2/Program.cs
> +                    goto label1;
I have removed the goto statements.

2023-08-28 06:47 UTC, aristovinceselvanathan commented on src/Assignment2/Program.cs
> +            int id, i;
I have changed the variable name more meaningful.

2023-08-28 06:51 UTC, aristovinceselvanathan commented on src/Assignment2/Program.cs
> +                try
I have used int.TryParse() for handle the invalid input.

2023-08-28 06:56 UTC, aristovinceselvanathan commented on src/Assignment2/Program.cs
> +        public static Person? SearchandRemove()
I have renamed the method name.

2023-08-28 07:02 UTC, aristovinceselvanathan commented on src/Assignment2/Program.cs
> +            int t;
I have changed the variable declaration more meaningful.

2023-08-28 07:04 UTC, aristovinceselvanathan commented on src/Assignment2/Program.cs
> +                        case 1:
I have resolved the variable

2023-08-28 07:05 UTC, aristovinceselvanathan commented on src/Assignment2/Program.cs
> +            bool phonec = person.SetPhone(phone);
I have changed the variable declaration more meaningful manner.

2023-08-28 07:06 UTC, aristovinceselvanathan commented on src/Assignment2/Assignment2.csproj
> +    </PackageReference>
Alignment is made proper.

2023-08-28 07:07 UTC, aristovinceselvanathan commented on src/Assignment2/Person.cs
> +        private string Name { get; set; }
I have updated the variable to be private and removed the get and set.

2023-08-28 07:08 UTC, aristovinceselvanathan commented on src/Assignment2/Program.cs
> +        private static List<Person> list = new List<Person>();
I have made this to be non static and named in meaningful way.

2023-08-28 07:09 UTC, aristovinceselvanathan commented on src/Assignment2/Program.cs
> +            int choose, option;
Variables names are updated more meaningful manner.

2023-08-28 07:12 UTC, aristovinceselvanathan commented on src/Assignment2/Program.cs
> +                Console.Write("Actions 1.Add 2.Remove 3.Search 4.Displyall 5.Exit: ");
I have updated the option

2023-08-28 07:13 UTC, aristovinceselvanathan commented on src/Assignment2/Program.cs
> +                int.TryParse(Console.ReadLine(), out choose);
I have check the TryParse by the if condition .

2023-08-28 07:14 UTC, aristovinceselvanathan commented on src/Assignment2/Program.cs
> +                        Console.Write("Name: ");
I have added more description in the console.WriteLine();

2023-08-28 07:15 UTC, aristovinceselvanathan commented on src/Assignment2/Program.cs
> +                        if (IsValidString(name))
I have added to the person class

2023-08-28 07:19 UTC, aristovinceselvanathan commented on src/Assignment2/Program.cs
> +        public static Person? PersonSearch()
Function name is changed to more meaningful way.

2023-08-28 07:20 UTC, aristovinceselvanathan commented on src/Assignment2/Program.cs
> +        public static string CheckStringIsNull(string? input)
I have removed the function.

2023-08-28 07:22 UTC, aristovinceselvanathan commented on src/Assignment2/Program.cs
> +        public static bool IsValidString(string input)
I have renamed to check the name is valid.

2023-08-28 07:23 UTC, aristovinceselvanathan commented on src/Assignment2/Program.cs
> +        public static void Displayall()
I have changed to Pascal case.

2023-08-28 12:41 UTC, sandeep-sol requested changes

2023-08-28 12:41 UTC, sandeep-sol commented on src/Assignment2/Person.cs
> +        private string _additionalnotes;
This should be in the camel case. Please update it.

2023-08-28 12:41 UTC, sandeep-sol commented on src/Assignment2/Program.cs
> +            Program userInterface = new Program();
This is not advisable. Why are you creating an object of the Program class here?

2023-08-28 12:41 UTC, sandeep-sol commented on src/Assignment2/Program.cs
> +                        case 1:
Please use enums instead of constant values.

2023-08-28 12:41 UTC, sandeep-sol commented on src/Assignment2/Program.cs
> +        /// <param name="name">It takes the string as parameter for name</param>
This comment must describe what this parameter is for... 

For example, you can use something like `Name of the person`.

2023-08-28 12:41 UTC, sandeep-sol commented on src/Assignment2/Program.cs
> +                            if (person != null && userInterface.Remove(person, phoneDirectory))
What if the person value is equal to `null`. Will it give a meaningful message to user?

2023-08-28 12:41 UTC, sandeep-sol commented on src/Assignment2/Program.cs
> +                            if (person != null && userInterface.Remove(person, phoneDirectory))
Same question for the case 3.

2023-08-28 12:41 UTC, sandeep-sol commented on src/Assignment2/Program.cs
> +                    Console.Write("Enter Search: ");
What if the option is out of range?

2023-08-28 12:41 UTC, sandeep-sol commented on src/Assignment2/Program.cs
> +                int.TryParse(Console.ReadLine(), out int id);
What are you expecting the user to enter here? It's not clear from what you've given.

2023-08-28 13:25 UTC, aristovinceselvanathan commented on src/Assignment2/Program.cs
> +                int.TryParse(Console.ReadLine(), out int id);
If the multiple contacts are existing in the same name means it will let the user to choose the person

2023-08-28 13:30 UTC, aristovinceselvanathan commented on src/Assignment2/Person.cs
> +        private string _additionalnotes;
I have changed it.

2023-08-28 13:31 UTC, aristovinceselvanathan commented on src/Assignment2/Program.cs
> +        /// <param name="name">It takes the string as parameter for name</param>
I have changed it.

2023-08-28 13:31 UTC, aristovinceselvanathan commented on src/Assignment2/Program.cs
> +                            if (person != null && userInterface.Remove(person, phoneDirectory))
I have updated the conditions

2023-08-28 13:31 UTC, aristovinceselvanathan commented on src/Assignment2/Program.cs
> +                    Console.Write("Enter Search: ");
I have handled using the if condition

2023-08-29 09:33 UTC, aristovinceselvanathan commented on src/Assignment2/Program.cs
> +            Program userInterface = new Program();
I have updated

2023-08-29 09:33 UTC, aristovinceselvanathan commented on src/Assignment2/Program.cs
> +                        case 1:
I have used the Enum to declare the switch case

2023-08-30 09:21 UTC, sandeep-sol approved these changes
There are still some cases that are failing. If possible, please look into those.

2023-09-01 04:03 UTC, merged