feat: assignment 4 circular dependencies projects files update
aristovinceselvanathan/TIPS pull request #5
Opened 2023-08-21 12:06 UTC by aristovinceselvanathan

2023-09-03 17:14 UTC, sandeep-sol requested changes

2023-09-03 17:14 UTC, sandeep-sol commented on CSharp_Assignments.sln
The assignment document says that the solution should be named as `CSharpConsoleSolution` but it's different here.

2023-09-03 17:14 UTC, sandeep-sol commented on src/Assignment4/ProjectAGreetingsApp/ProgramA.cs
> +            string isNumber1, isNumber2;
The names should reflect what it does. Here it's not really making sense.

2023-09-03 17:14 UTC, sandeep-sol commented on src/Assignment4/ProjectAGreetingsApp/ProgramA.cs
> +                else
Does having `else` here is really useful?

2023-09-03 17:14 UTC, sandeep-sol commented on src/Assignment4/ProjectAGreetingsApp/ProgramA.cs
> +                    if (!int.TryParse(Console.ReadLine(), out option) || (option > 6 || option < 1))
Nice one!!

2023-09-03 17:14 UTC, sandeep-sol commented on src/Assignment4/ProjectBMathApp/ProgramB.cs
> +    public class ProgramB : InterfaceE
What do you expect this class to do?

If it just exposes functions for doing Math operations, then what is the need for main method?

2023-09-03 17:14 UTC, sandeep-sol commented on src/Assignment4/ProjectCDisplayApp/ProgramC.cs
> +        public void Get(InterfaceE t1)
Please update this function. This is not understandable.

2023-09-03 17:14 UTC, sandeep-sol commented on src/Assignment4/ProjectCDisplayApp/ProgramC.cs
> +        /// Method display that display the result based on the operations that user choose.
Typo mistake in the summary.

2023-09-03 17:14 UTC, sandeep-sol commented on src/Assignment4/ProjectCDisplayApp/ProgramC.cs
> +        /// <param name="input1">It takes the input1</param>
This is a description of what the parameter is and not about what argument this function takes. Those 2 have completely different meanings.

2023-09-03 17:14 UTC, sandeep-sol commented on src/Assignment4/ProjectCDisplayApp/ProgramC.cs
> +        private static InterfaceE temp;
What is `temp`?

2023-09-03 17:14 UTC, sandeep-sol commented on src/Assignment4/ProjectEHelperApp/InterfaceE.cs
> +        public static void Main(string[] args)
Why is there a `Main` method in an interface?

2023-09-04 06:21 UTC, aristovinceselvanathan commented on CSharp_Assignments.sln
I have resolved it.

2023-09-04 06:22 UTC, aristovinceselvanathan commented on src/Assignment4/ProjectAGreetingsApp/ProgramA.cs
> +            string isNumber1, isNumber2;
I Have changed the variable name to be more meaningful.

2023-09-04 06:22 UTC, aristovinceselvanathan commented on src/Assignment4/ProjectBMathApp/ProgramB.cs
> +    public class ProgramB : InterfaceE
I have removed the main method

2023-09-04 06:23 UTC, aristovinceselvanathan commented on src/Assignment4/ProjectCDisplayApp/ProgramC.cs
> +        public void Get(InterfaceE t1)
I have named the method to be meaningful.

2023-09-04 06:23 UTC, aristovinceselvanathan commented on src/Assignment4/ProjectCDisplayApp/ProgramC.cs
> +        /// <param name="input1">It takes the input1</param>
Parameter comments are described in detail.

2023-09-04 06:24 UTC, aristovinceselvanathan commented on src/Assignment4/ProjectCDisplayApp/ProgramC.cs
> +        private static InterfaceE temp;
I have changed the name.

2023-09-04 06:24 UTC, aristovinceselvanathan commented on src/Assignment4/ProjectEHelperApp/InterfaceE.cs
> +        public static void Main(string[] args)
I have removed the main method.

2023-09-04 06:25 UTC, aristovinceselvanathan commented on src/Assignment4/ProjectAGreetingsApp/ProgramA.cs
> +                else
I have changed the logic of the else block

2023-09-04 06:25 UTC, aristovinceselvanathan commented on src/Assignment4/ProjectCDisplayApp/ProgramC.cs
> +        /// Method display that display the result based on the operations that user choose.
Typo mistake is rectified.

2023-09-05 14:15 UTC, sandeep-sol approved these changes

2023-09-06 06:14 UTC, merged