Feat: assignment 6 oops concept
aristovinceselvanathan/TIPS pull request #6
Opened 2023-08-22 16:33 UTC by aristovinceselvanathan

2023-09-10 07:18 UTC, sandeep-sol requested changes

2023-09-10 07:18 UTC, sandeep-sol commented on src/Assignment6/Shape_Hierarchy/Shape.cs
> +        /// It sets the colour, Input1 and Input2 of the dimensions of the shapes
Remove this line. It is unnecessary. The param descriptions will take care of describing the parameters.

2023-09-10 07:18 UTC, sandeep-sol commented on src/Assignment6/Shape_Hierarchy/Shape.cs
> +        /// <param name="colour">It takes the colour as a string</param>
```suggestion
        /// <param name="colour">Color of the shape.</param>
```

Update all the param and method descriptions similar to this.

2023-09-10 07:18 UTC, sandeep-sol commented on src/Assignment6/Shape_Hierarchy/Rectangle.cs
> +    /// Rectangle class that inherits the shape class
The class description should not contain info about the base class.

2023-09-10 07:18 UTC, sandeep-sol commented on src/Assignment6/Shape_Hierarchy/Rectangle.cs
> +            Console.WriteLine("It is a Rectangle Class");
For what this console message is needed?

2023-09-10 07:18 UTC, sandeep-sol commented on src/Assignment6/Shape_Hierarchy/Shape.cs
> +        protected string Colour { get; set; }
Should this be `Public`?

2023-09-10 07:18 UTC, sandeep-sol commented on src/Assignment6/Shape_Hierarchy/Program.cs
> +            string colorOfCircle, colorOfRectangle, isDoubleOfRadius, isDoubleOfRectangle, isDoubleOfBreath;
```suggestion
            string colorOfCircle, colorOfRectangle, isDoubleOfRadius, isDoubleOfRectangle, isDoubleOfBreadth;
```

2023-09-10 07:18 UTC, sandeep-sol commented on src/Assignment6/Shape_Hierarchy/Program.cs
> +            string colorOfCircle, colorOfRectangle, isDoubleOfRadius, isDoubleOfRectangle, isDoubleOfBreath;
isDoubleOfRadius, isDoubleOfRectangle, isDoubleOfBreath

These variable names are not meaningful. Please update it.

2023-09-10 07:18 UTC, sandeep-sol commented on src/Assignment6/Shape_Hierarchy/Program.cs
> +        public static bool IsColorName(string s)
IsColorName, InvalidWarning

These function names are not meaningful. Please update it.

2023-09-10 07:18 UTC, sandeep-sol commented on src/Assignment6/Shape_Hierarchy/Program.cs
> +            Regex r = new Regex("^[a-zA-Z\\s]+$");
It's good that you've validated this.

2023-09-10 07:18 UTC, sandeep-sol commented on src/Assignment6/Shape_Hierarchy/Shape_Hierarchy.csproj
Don't use underscore in-between folder names, class names, and namespaces.

Update it in all the places.

2023-09-10 07:18 UTC, sandeep-sol commented on src/Assignment6/Employee_Hierarchy/Employee.cs
> +        public Employee(string name, decimal salary)
Why decimal?

2023-09-10 07:18 UTC, sandeep-sol commented on src/Assignment6/Employee_Hierarchy/Program.cs
> +                            case 1:
Should use enum here.

2023-09-10 07:18 UTC, sandeep-sol commented on src/Assignment6/Employee_Hierarchy/Program.cs
> +            string isValidName, isValidDecimal;
Shouldn't these be of type `bool`?

2023-09-10 07:18 UTC, sandeep-sol commented on src/Assignment6/Employee_Hierarchy/Program.cs
> +                    if (int.TryParse(Console.ReadLine(), out optionOfTypeOfRole))
Logically, this should have been the first input.

2023-09-10 07:18 UTC, sandeep-sol commented on src/Assignment6/Employee_Hierarchy/Program.cs
> +            Console.WriteLine("Did you want print the details : Y or N");
Why are these console messages in past tense?

2023-09-10 07:18 UTC, sandeep-sol commented on src/Assignment6/Banking_System/BankAccount.cs
> +        }
These functions should not be a part of this class. Please move them.

And also the names are not meaningful. Please update them.

2023-09-10 07:18 UTC, sandeep-sol commented on src/Assignment6/Banking_System/BankAccount.cs
> +            }
Is this implementation necessary?

Applicable to all the 3 projects.

2023-09-10 07:18 UTC, sandeep-sol commented on src/Assignment6/Banking_System/Program.cs
> +        public static bool IsNumberValid(string s)
The method name can be more specific.

2023-09-11 08:42 UTC, aristovinceselvanathan commented on src/Assignment6/Shape_Hierarchy/Shape.cs
> +        /// It sets the colour, Input1 and Input2 of the dimensions of the shapes
I have changed it.

2023-09-11 08:46 UTC, aristovinceselvanathan commented on src/Assignment6/Shape_Hierarchy/Shape.cs
> +        /// <param name="colour">It takes the colour as a string</param>
I have resolved it.

2023-09-11 08:46 UTC, aristovinceselvanathan commented on src/Assignment6/Shape_Hierarchy/Rectangle.cs
> +    /// Rectangle class that inherits the shape class
I have changed the base classes description.

2023-09-11 08:48 UTC, aristovinceselvanathan commented on src/Assignment6/Shape_Hierarchy/Rectangle.cs
> +            Console.WriteLine("It is a Rectangle Class");
I have removed the message.

2023-09-11 08:49 UTC, aristovinceselvanathan commented on src/Assignment6/Shape_Hierarchy/Shape.cs
> +        protected string Colour { get; set; }
I have made to Public.

2023-09-11 08:49 UTC, aristovinceselvanathan commented on src/Assignment6/Shape_Hierarchy/Program.cs
> +            string colorOfCircle, colorOfRectangle, isDoubleOfRadius, isDoubleOfRectangle, isDoubleOfBreath;
I have changed the variable names.

2023-09-11 08:50 UTC, aristovinceselvanathan commented on src/Assignment6/Shape_Hierarchy/Program.cs
> +            string colorOfCircle, colorOfRectangle, isDoubleOfRadius, isDoubleOfRectangle, isDoubleOfBreath;
Variable names are updated.

2023-09-11 08:50 UTC, aristovinceselvanathan commented on src/Assignment6/Shape_Hierarchy/Program.cs
> +        public static bool IsColorName(string s)
Function name is updated

2023-09-11 09:15 UTC, aristovinceselvanathan commented on src/Assignment6/Shape_Hierarchy/Shape_Hierarchy.csproj
I have changed it

2023-09-11 09:16 UTC, aristovinceselvanathan commented on src/Assignment6/Employee_Hierarchy/Employee.cs
> +        public Employee(string name, decimal salary)
I have changed it

2023-09-11 09:16 UTC, aristovinceselvanathan commented on src/Assignment6/Employee_Hierarchy/Program.cs
> +                            case 1:
I have used the enum in that switch case

2023-09-11 09:17 UTC, aristovinceselvanathan commented on src/Assignment6/Employee_Hierarchy/Program.cs
> +            string isValidName, isValidDecimal;
I have updated the one.

2023-09-11 09:17 UTC, aristovinceselvanathan commented on src/Assignment6/Employee_Hierarchy/Program.cs
> +                    if (int.TryParse(Console.ReadLine(), out optionOfTypeOfRole))
I have changed the logic

2023-09-11 09:18 UTC, aristovinceselvanathan commented on src/Assignment6/Employee_Hierarchy/Program.cs
> +            Console.WriteLine("Did you want print the details : Y or N");
I have changed the console messages

2023-09-11 09:18 UTC, aristovinceselvanathan commented on src/Assignment6/Banking_System/BankAccount.cs
> +        }
I have moved the logic

2023-09-11 09:18 UTC, aristovinceselvanathan commented on src/Assignment6/Banking_System/Program.cs
> +        public static bool IsNumberValid(string s)
I have changed the method name

2023-09-14 15:34 UTC, sandeep-sol approved these changes

2023-09-14 15:34 UTC, sandeep-sol commented on src/Assignment1/Assignment1.csproj
> +  <ItemGroup>
Why are these changes added here?

Same for Assignment2 and Assignment4 projects.

2023-09-14 15:34 UTC, sandeep-sol commented on src/Assignment6/BankingSystem/Program.cs
> +        public static void Services(BankAccount user)
```suggestion
        public static void Services(BankAccount userAccount)
```

2023-09-15 03:36 UTC, aristovinceselvanathan commented on src/Assignment6/BankingSystem/Program.cs
> +        public static void Services(BankAccount user)
I have resolved it.

2023-09-15 06:35 UTC, merged