Feat assignment 7 git in visual studio
aristovinceselvanathan/TIPS pull request #8
Opened 2023-09-01 09:35 UTC by aristovinceselvanathan

2023-09-10 07:32 UTC, sandeep-sol requested changes

2023-09-10 07:32 UTC, sandeep-sol commented on src/Assignment7/Git/Readme.md
> +![Alt text](<Screenshot (13).png>)
Please update the name of the screenshots such that it describes what is shown.

2023-09-10 07:32 UTC, sandeep-sol commented on src/Assignment7/Git/Screenshot (6)-1.png
This image is a duplicate. Is this intentional?

2023-09-10 07:32 UTC, sandeep-sol commented on src/Assignment7/Git/Screenshot (10).png
The task says that you should make several changes in a file and commit those changes selectively. But this has changes in 2 files and one of them is staged.

This is not expected. Please update it.

2023-09-10 07:32 UTC, sandeep-sol commented on src/Assignment7/Git/Readme.md
> +Main method just prints the required informations like Hello World, How are you etc.
```suggestion
The main method just prints the required information like Hello World, How are you, etc.
```

2023-09-10 07:32 UTC, sandeep-sol commented on src/Assignment7/Git/Readme.md
> +- Resolving the merge confilct between the branches
```suggestion
- Resolving the merge conflicts between the branches
```

2023-09-10 07:32 UTC, sandeep-sol commented on src/Assignment7/Git/Readme.md
> +- Creating the new branch from the current branch
```suggestion
- Creating a new branch from the current branch
```

2023-09-10 07:32 UTC, sandeep-sol commented on src/Assignment7/Git/Readme.md
> +2. Open Visual Studio and createa new project. Choose a simple console application for this assignment.<br><br>
```suggestion
2. Open Visual Studio and create a new project. Choose a simple console application for this assignment.<br><br>
```

2023-09-10 07:32 UTC, sandeep-sol commented on src/Assignment7/Git/Readme.md
> +1. Writea meaningful commit message describing the changes you made.
```suggestion
1. Write a meaningful commit message describing the changes you made.
```

2023-09-10 07:32 UTC, sandeep-sol commented on src/Assignment7/Git/Readme.md
> +The assignemnt that can able to understand the concept of the git in Visual Studio by the use of the git chages window. Became familar with the window.
Please update this statement.

2023-09-10 07:32 UTC, sandeep-sol commented on src/Assignment7/Git/Readme.md
> +![Alt text](<Screenshot (10).png>)<br>
It's good that you've added all these screenshots for reference.

2023-09-10 07:32 UTC, sandeep-sol commented on src/Assignment7/Git/Screenshot (10).png
Move all the screenshots to a folder.

2023-09-11 10:26 UTC, aristovinceselvanathan commented on src/Assignment7/Git/Readme.md
> +![Alt text](<Screenshot (13).png>)
I have resolved it

2023-09-11 10:26 UTC, aristovinceselvanathan commented on src/Assignment7/Git/Screenshot (6)-1.png
I have removed the file

2023-09-11 10:26 UTC, aristovinceselvanathan commented on src/Assignment7/Git/Screenshot (10).png
I have changed the screenshot

2023-09-11 10:26 UTC, aristovinceselvanathan commented on src/Assignment7/Git/Readme.md
> +Main method just prints the required informations like Hello World, How are you etc.
I have changed the statement

2023-09-11 10:27 UTC, aristovinceselvanathan commented on src/Assignment7/Git/Readme.md
> +- Resolving the merge confilct between the branches
I have changed the statement

2023-09-11 10:27 UTC, aristovinceselvanathan commented on src/Assignment7/Git/Readme.md
> +- Creating the new branch from the current branch
I have changed the statement

2023-09-11 10:27 UTC, aristovinceselvanathan commented on src/Assignment7/Git/Readme.md
> +2. Open Visual Studio and createa new project. Choose a simple console application for this assignment.<br><br>
I have changed the statement

2023-09-11 10:27 UTC, aristovinceselvanathan commented on src/Assignment7/Git/Readme.md
> +1. Writea meaningful commit message describing the changes you made.
I Have changed the statement

2023-09-11 10:28 UTC, aristovinceselvanathan commented on src/Assignment7/Git/Readme.md
> +The assignemnt that can able to understand the concept of the git in Visual Studio by the use of the git chages window. Became familar with the window.
I have updated the statement

2023-09-11 10:28 UTC, aristovinceselvanathan commented on src/Assignment7/Git/Screenshot (10).png
I have moved the folder

2023-09-14 15:35 UTC, sandeep-sol approved these changes

2023-09-15 06:57 UTC, merged