Feat assignment 9 memory management 2
aristovinceselvanathan/TIPS pull request #9
Opened 2023-09-02 18:34 UTC by aristovinceselvanathan

2023-09-25 06:15 UTC, sandeep-sol requested changes

2023-09-25 06:15 UTC, sandeep-sol commented on src/Assignment9/ValueAndReferenceTypes/Program.cs
> +        }
The task asks to create only one function.

Having two functions will be more meaningful. But is it intentional?

2023-09-25 06:15 UTC, sandeep-sol commented on src/Assignment9/ValueAndReferenceTypes/Program.cs
> +        /// It will change the value by reference
Please change the format of this description.

Applicable for the other function and param descriptions.

Hope not to repeat this comment after this occurrence.

2023-09-25 06:15 UTC, sandeep-sol commented on src/Assignment9/ValueAndReferenceTypes/Program.cs
> +            employee.Id = "1001";
Please update the constructor of the `Employee` class to have these values by default.

2023-09-25 06:15 UTC, sandeep-sol commented on src/Assignment9/ValueAndReferenceTypes/Program.cs
> +        /// Method creates the large array of Integers.
The requirement is to extend the project and use it. Not to use the same project.

Please update it.

2023-09-25 06:15 UTC, sandeep-sol commented on src/Assignment9/Readme.md
> +# Documentation Report:
Please add your understanding of each topic/task in detail in this report.

2023-09-25 12:41 UTC, aristovinceselvanathan commented on src/Assignment9/ValueAndReferenceTypes/Program.cs
> +        }
I have updated the logic

2023-09-25 12:41 UTC, aristovinceselvanathan commented on src/Assignment9/ValueAndReferenceTypes/Program.cs
> +        /// It will change the value by reference
I have changed it

2023-09-25 12:42 UTC, aristovinceselvanathan commented on src/Assignment9/ValueAndReferenceTypes/Program.cs
> +            employee.Id = "1001";
I have declared it in constructor itself.

2023-09-25 12:43 UTC, aristovinceselvanathan commented on src/Assignment9/ValueAndReferenceTypes/Program.cs
> +        /// Method creates the large array of Integers.
I have extended to another project of Name ExtendedValueAndReferenceType.

2023-09-25 12:45 UTC, aristovinceselvanathan commented on src/Assignment9/Readme.md
> +# Documentation Report:
I have added the understandings of the each topic

2023-09-27 17:12 UTC, sandeep-sol requested changes

2023-09-27 17:12 UTC, sandeep-sol commented on src/Assignment9/ValueAndReferenceTypes/Employee.cs
> +        }
Generally, we should use a parameterized constructor for these cases. Please update this.

2023-09-27 17:12 UTC, sandeep-sol commented on src/Assignment9/ValueAndReferenceTypes/Employee.cs
> +        /// It sets the predefined value to the Employee object.
Please remove this statement. It is not necessary.

2023-09-27 17:12 UTC, sandeep-sol commented on src/Assignment9/ValueAndReferenceTypes/Program.cs
> +        /// <param name="args">It takes the string array from the command line interface</param>
I've already mentioned updating these types of param descriptions. Please update it in all the places.

2023-09-27 17:12 UTC, sandeep-sol commented on src/Assignment9/ValueAndReferenceTypes/Program.cs
> +            Console.WriteLine(employee);
This is not meaningful. Are these lines interchanged?

2023-09-27 17:12 UTC, sandeep-sol commented on src/Assignment9/ValueAndReferenceTypes/Program.cs
> +            Console.WriteLine($"Value is after calling the function to change value is {value}\n");
Typos.. Please update it...

2023-09-27 17:12 UTC, sandeep-sol commented on src/Assignment9/Readme.md
> +## Understandings of the Project
Expecting a detailed explanation of all of these.

2023-09-27 17:12 UTC, sandeep-sol commented on src/Assignment9/ValueAndReferenceTypes/Program.cs
> +            ExtendedValueAndReferenceType.LargeArray();
Please share your observations from these 2 function calls in this comment thread.

2023-09-28 09:47 UTC, aristovinceselvanathan commented on src/Assignment9/ValueAndReferenceTypes/Employee.cs
> +        }
I have created the constructor with parameters.

2023-09-28 09:48 UTC, aristovinceselvanathan commented on src/Assignment9/ValueAndReferenceTypes/Employee.cs
> +        /// It sets the predefined value to the Employee object.
I have removed the comment line

2023-09-28 09:48 UTC, aristovinceselvanathan commented on src/Assignment9/ValueAndReferenceTypes/Program.cs
> +        /// <param name="args">It takes the string array from the command line interface</param>
I have changed it.

2023-09-28 09:49 UTC, aristovinceselvanathan commented on src/Assignment9/ValueAndReferenceTypes/Program.cs
> +            Console.WriteLine(employee);
I have updated it.

2023-09-28 09:49 UTC, aristovinceselvanathan commented on src/Assignment9/ValueAndReferenceTypes/Program.cs
> +            Console.WriteLine($"Value is after calling the function to change value is {value}\n");
I have updated it.

2023-09-28 09:49 UTC, aristovinceselvanathan commented on src/Assignment9/ValueAndReferenceTypes/Program.cs
> +            ExtendedValueAndReferenceType.LargeArray();
I have commented on that line about the functionality of functions

2023-10-03 04:33 UTC, aristovinceselvanathan commented on src/Assignment9/Readme.md
> +## Understandings of the Project
I have added it

2023-10-04 15:32 UTC, sandeep-sol approved these changes

2023-10-05 12:31 UTC, merged